### ISSUE TITLE
[core-zero]mod charm support

### ISSUE THREAD

**Issue by Neilyo-X** [mangoszero/server#26]
all spells that used by creature to charm the player are unwork,maybe lack of core support(sorry for my poor english)

**Comment by Neilyo-X** [comment]
i have found one core which the charm systerm is work right.
i will post the code but it is used in TC,not for mangos.
i can not read the code very clear.
maybe others will have some idea
===================================================
void Aura::HandleModPossess(bool apply, bool Real)
{
    if(!Real)
        return;

    Unit* caster = GetCaster();
    if(caster && caster->GetTypeId() == TYPEID_UNIT)
    {
        HandleModCharm(apply, Real);
        return;
    }

    if(apply)
    {
        if(m_target->getLevel() > m_modifier.m_amount)
            return;

        m_target->SetCharmedOrPossessedBy(caster, true);
    }
    else
        m_target->RemoveCharmedOrPossessedBy(caster);
}
===============================================
Unit* Unit::GetCharm() const
{
    if(uint64 charm_guid = GetCharmGUID())
    {
        if(Unit* pet = ObjectAccessor::GetUnit(*this, charm_guid))
            return pet;

        sLog.outError("Unit::GetCharm: Charmed creature %u not exist.",GUID_LOPART(charm_guid));
        const_cast<Unit*>(this)->SetCharm(0);
    }

    return NULL;
}
===============================================
void Unit::SetCharm(Unit* pet)
{
    if(GetTypeId() == TYPEID_PLAYER)
        SetUInt64Value(UNIT_FIELD_CHARM, pet ? pet->GetGUID() : 0);
}
================================================
void Unit::SetCharmedOrPossessedBy(Unit* charmer, bool possess)
{
    if(!charmer)
        return;

    assert(!possess || charmer->GetTypeId() == TYPEID_PLAYER);

    if(this == charmer)
        return;

    if(isInFlight())
        return;

    if(GetTypeId() == TYPEID_PLAYER && ((Player*)this)->GetTransport())
        return;

    RemoveUnitMovementFlag(MOVEMENTFLAG_WALK_MODE);
    CastStop();
    CombatStop(); //TODO: CombatStop(true) may cause crash (interrupt spells)
    DeleteThreatList();

    // Charmer stop charming
    if(charmer->GetTypeId() == TYPEID_PLAYER)
        ((Player*)charmer)->StopCastingCharm();

    // Charmed stop charming
    if(GetTypeId() == TYPEID_PLAYER)
        ((Player*)this)->StopCastingCharm();

    // StopCastingCharm may remove a possessed pet?
    if(!IsInWorld())
        return;

    // Set charmed
    charmer->SetCharm(this);
    SetCharmerGUID(charmer->GetGUID());
    setFaction(charmer->getFaction());
    SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PVP_ATTACKABLE);

    if(GetTypeId() == TYPEID_UNIT)
    {
        ((Creature*)this)->AI()->OnCharmed(true);
        GetMotionMaster()->Clear(false);
        GetMotionMaster()->MoveIdle();
    }
    else
    {
        if(((Player*)this)->isAFK())
            ((Player*)this)->ToggleAFK();
        ((Player*)this)->SetViewport(GetGUID(), false);
    }

    // Pets already have a properly initialized CharmInfo, don't overwrite it.
    if(GetTypeId() == TYPEID_PLAYER || GetTypeId() == TYPEID_UNIT && !((Creature*)this)->isPet())
    {
        CharmInfo *charmInfo = InitCharmInfo();
        if(possess)
            charmInfo->InitPossessCreateSpells();
        else
            charmInfo->InitCharmCreateSpells();
    }

    //Set possessed
    if(possess)
    {
        addUnitState(UNIT_STAT_POSSESSED);
        SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_UNKNOWN5);
        AddPlayerToVision((Player*)charmer);
        ((Player*)charmer)->SetViewport(GetGUID(), true);
        charmer->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
    }
    // Charm demon
    else if(GetTypeId() == TYPEID_UNIT && charmer->GetTypeId() == TYPEID_PLAYER && charmer->getClass() == CLASS_WARLOCK)
    {
        CreatureInfo const *cinfo = ((Creature*)this)->GetCreatureInfo();
        if(cinfo && cinfo->type == CREATURE_TYPE_DEMON)
        {
            //to prevent client crash
            SetFlag(UNIT_FIELD_BYTES_0, 2048);

            //just to enable stat window
            if(GetCharmInfo())
                GetCharmInfo()->SetPetNumber(objmgr.GeneratePetNumber(), true);

            //if charmed two demons the same session, the 2nd gets the 1st one's name
            SetUInt32Value(UNIT_FIELD_PET_NAME_TIMESTAMP, time(NULL));
        }
    }

    if(possess)
        ((Player*)charmer)->PossessSpellInitialize();
    else if(charmer->GetTypeId() == TYPEID_PLAYER)
        ((Player*)charmer)->CharmSpellInitialize();
}

void Unit::RemoveCharmedOrPossessedBy(Unit *charmer)
{
    if(!isCharmed())
        return;

    if(!charmer)
        charmer = GetCharmer();
    else if(charmer != GetCharmer()) // one aura overrides another?
        return;

    bool possess = hasUnitState(UNIT_STAT_POSSESSED);

    CastStop();
    CombatStop(); //TODO: CombatStop(true) may cause crash (interrupt spells)
    getHostilRefManager().deleteReferences();
    DeleteThreatList();
    SetCharmerGUID(0);
    RestoreFaction();

    if(possess)
    {
        clearUnitState(UNIT_STAT_POSSESSED);
        RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_UNKNOWN5);
    }

    if(GetTypeId() == TYPEID_UNIT)
    {
        if(!((Creature*)this)->isPet())
            RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PVP_ATTACKABLE);

        ((Creature*)this)->AI()->OnCharmed(false);
        if(isAlive() && ((Creature*)this)->IsAIEnabled)
        {
            if(charmer && !IsFriendlyTo(charmer))
            {
                ((Creature*)this)->AddThreat(charmer, 10000.0f);
                ((Creature*)this)->AI()->AttackStart(charmer);
            }
            else
                ((Creature*)this)->AI()->EnterEvadeMode();
        }
    }
    else
        ((Player*)this)->SetViewport(GetGUID(), true);

    // If charmer still exists
    if(!charmer)
        return;

    assert(!possess || charmer->GetTypeId() == TYPEID_PLAYER);

    charmer->SetCharm(0);
    if(possess)
    {
        RemovePlayerFromVision((Player*)charmer);
        ((Player*)charmer)->SetViewport(charmer->GetGUID(), true);
        charmer->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
    }
    // restore UNIT_FIELD_BYTES_0
    else if(GetTypeId() == TYPEID_UNIT && charmer->GetTypeId() == TYPEID_PLAYER && charmer->getClass() == CLASS_WARLOCK)
    {
        CreatureInfo const *cinfo = ((Creature*)this)->GetCreatureInfo();
        if(cinfo && cinfo->type == CREATURE_TYPE_DEMON)
        {
            CreatureDataAddon const *cainfo = ((Creature*)this)->GetCreatureAddon();
            if(cainfo && cainfo->bytes0 != 0)
                SetUInt32Value(UNIT_FIELD_BYTES_0, cainfo->bytes0);
            else
                RemoveFlag(UNIT_FIELD_BYTES_0, 2048);

            if(GetCharmInfo())
                GetCharmInfo()->SetPetNumber(0, true);
            else
                sLog.outError("Aura::HandleModCharm: target="I64FMTD" with typeid=%d has a charm aura but no charm info!", GetGUID(), GetTypeId());
        }
    }

    if(GetTypeId() == TYPEID_PLAYER || GetTypeId() == TYPEID_UNIT && !((Creature*)this)->isPet())
    {
        DeleteCharmInfo();
    }

    if(possess || charmer->GetTypeId() == TYPEID_PLAYER)
    {
        // Remove pet spell action bar
        WorldPacket data(SMSG_PET_SPELLS, 8);
        data << uint64(0);
        ((Player*)charmer)->GetSession()->SendPacket(&data);
    }
}

void Unit::RestoreFaction()
{
    if(GetTypeId() == TYPEID_PLAYER)
        ((Player*)this)->setFactionForRace(getRace());
    else
    {
        CreatureInfo const *cinfo = ((Creature*)this)->GetCreatureInfo();

        if(((Creature*)this)->isPet())
        {
            if(Unit* owner = GetOwner())
                setFaction(owner->getFaction());
            else if(cinfo)
                setFaction(cinfo->faction_A);
        }
        else if(cinfo)  // normal creature
            setFaction(cinfo->faction_A);
    }
}
=============================================
sorry  i know it is hard to read.
but this is all the files i can find,maybe will help others to fix the mod charm systerm

**Comment by MadMaxMangos** [comment]
Issue migrated to: https://www.getmangos.eu/issue.php?issueid=932

Please use the getmangos.eu site for all future responses as github issues will be disabled after this reply.
