### ISSUE TITLE
x64 Compile settings

### ISSUE THREAD

**Issue by bwaiox** [mangoszero/server#7]
Hi, all,

I downloaded the release 20 code, and try to compile the X64 version of mangos with my vs2013,
I create the x64 solution platforms settings at solution manager. The complier tell me "fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86' "
I checked the setting at Property pages->Linker->Advanced->Targert machine and it is X64. 
I googled a lot, finally i got where the problem there is a " /machine:X86" at Property pages->Linker->Command Line->additional options.   I got compile passed after delete it.

so, could anyone fix it?  because I'm new to git / git hub , I don't know how to upload my fixed x64 setting vcproj file up.

**Comment by billy1arm** [comment]
@bwaiox - although the old projects allowed a 64 bit build, there are several areas of mangos structure that are not correctly coded for reliable 64 usage.

Therefore the 'prepared' solutions in the win folder are only available in 32 bit .

The New cmake system fully windows compatible, so using cmake you can generate a 64 bit solution file if that is your wish.

The cmake system also allows you to specify which modules to activate/deactivate - which is not possible in the prepared solutions.

**Comment by bwaiox** [comment]
@billy1arm Oh, I see. I'll try cmake. Thank you for give me guide. Thank you.
